services:
  php-apache:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=tastyigniter
      - DB_USERNAME=tastyigniter
      - DB_PASSWORD=tastyigniter
      - APP_DEBUG=true

  db:
    # Use root/example as user/password credentials
    image: mysql:9.0.1
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --general_log_file="/var/log/mysql/mysql.log" --general_log=1
    environment:
      - MYSQL_DATABASE=tastyigniter
      - MYSQL_USER=tastyigniter
      - MYSQL_PASSWORD=tastyigniter
      - MYSQL_ROOT_PASSWORD=example
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  # to view db if necessary
  adminer:
    image: adminer
    ports:
      - 8080:8080
